version: "3.4"
services:
  bondcard:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/public
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
